# Specific Dockerfile for your C proejcts.
# C environment

FROM ubuntu

RUN apt-get update && \
	apt-get upgrade -y && \
	apt-get install -y build-essential git vim

#docker build -t bo01 .
#docker run --rm -it bo01
